Update `backend-deploy-coverage-report.yaml` GitHub Actions To Support Rebuild Of Failed Commits
In case the build is run by hand over and over again,
it will create a new id for each artifact to it,
so it could be distinguished from the old artifacts of that commit.

This fixes the following GitHub Actions problems:

```
Fetching artifact metadata for "github-pages" in this workflow run
Found 3 artifact(s)
Error: Fetching artifact metadata failed. Is githubstatus.com reporting issues with API requests, Pages, or Actions? Please re-run the deployment at a later time.
Error: Error: Multiple artifacts named "github-pages" were unexpectedly found for this workflow run. Artifact count is 3.
    at getArtifactMetadata (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/api-client.js:89:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/deployment.js:66:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v4/src/index.js:30:1)
Error: Error: Multiple artifacts named "github-pages" were unexpectedly found for this workflow run. Artifact count is 3.
```

Signed-off-by: Tal Jacob <taljacob2@gmail.com>